Repository Wymowny/project-wdp-2003-01, pull requests merged in 2020-03, with the labels that each got.

#2 WDP200301-4
  .gitignore
  package-lock.json
  src/components/common/ProductBox/ProductBox.module.scss
Labels: ready to merge

#3 WDP200301-3
  src/components/common/FeatureBox/FeatureBox.js
  src/components/common/FeatureBox/FeatureBox.module.scss
  src/components/features/FeatureBoxes/FeatureBoxes.js
Labels: ready to merge

#4 WDP200301-5
  src/components/common/Button/Button.js
  src/components/common/Button/Button.module.scss
  src/components/common/ProductBox/ProductBox.js
  src/redux/initialState.js
Labels: ready to merge

#5 WDP200301-6
  README.md
  src/components/common/Button/Button.module.scss
  src/components/common/ProductBox/ProductBox.js
  src/components/common/ProductBox/ProductBox.module.scss
  src/redux/initialState.js
  src/styles/settings.scss
Labels: conflicts, needs work

#6 Add styles to ProductSearch.modules class select
  package-lock.json
  src/components/features/ProductSearch/ProductSearch.module.scss
Labels: conflicts

#8 WDP200301-16
  src/components/common/FeatureBox/FeatureBox.module.scss
  src/components/features/FeatureBoxes/FeatureBoxes.js
  src/components/features/FeatureBoxes/FeatureBoxes.module.scss
Labels: ready to merge

#9 Add variable for colors in styles
  src/components/common/Button/Button.module.scss
  src/components/common/FeatureBox/FeatureBox.module.scss
  src/components/common/ProductBox/ProductBox.module.scss
  src/components/features/NewFurniture/NewFurniture.module.scss
  src/components/layout/CompanyClaim/CompanyClaim.module.scss
  src/components/layout/Footer/Footer.module.scss
  src/components/layout/MenuBar/MenuBar.module.scss
  src/components/layout/TopBar/TopBar.module.scss
  src/styles/settings.scss
Labels: ready to merge

#10 WDP200301-18
  src/components/layout/Footer/Footer.js
Labels: ready to merge

#14 wdp-2003-01-09 (add animation to hover --> uploaded reviev (16.03.20)
  package-lock.json
  src/components/common/Button/Button.module.scss
  src/components/layout/CompanyClaim/CompanyClaim.module.scss
  src/components/layout/MenuBar/MenuBar.module.scss
  src/styles/settings.scss
Labels: ready to merge

#13 WDP200301-11
  src/components/common/ProductBox/ProductBox.js
  src/components/common/ProductBox/ProductBoxContainer.js
  src/components/features/NewFurniture/NewFurniture.js
  src/redux/productsRedux.js
Labels: ready to merge

#17 WDP200301-17
  src/components/features/NewFurniture/NewFurniture.js
Labels: needs work

#15 WIP: wdp200301 15 <=> RWD - topbar i banner--> uploaded reviev (16.03.20) cosmetic changes in code
  README.md
  src/components/layout/CompanyClaim/CompanyClaim.js
  src/components/layout/CompanyClaim/CompanyClaim.module.scss
  src/components/layout/TopBar/TopBar.js
  src/components/layout/TopBar/TopBar.module.scss
Labels: needs work

#18 WDP200301-19 - Add new furniture animation
  src/components/common/ProductBox/ProductBox.module.scss
  src/components/features/NewFurniture/NewFurniture.js
  src/redux/initialState.js
  src/styles/settings.scss
Labels: needs work

#7 WIP: WDP200301-1
  public/images/products/beds/bed1.jpeg
  public/images/products/beds/bed2.jpeg
  public/images/products/beds/bed3.jpeg
  public/images/products/beds/bed4.jpeg
  public/images/products/beds/bed5.jpeg
  public/images/products/beds/bed6.jpeg
  src/components/common/ProductBox/ProductBox.js
  src/components/common/ProductBox/ProductBox.module.scss
  src/redux/initialState.js
Labels: conflicts, needs work, question

#26 WDP200301-33
  public/images/man.jpg
  src/components/common/Review/Review.js
  src/components/common/Review/Review.module.scss
  src/components/features/ClientFeedback/ClientFeedback.js
  src/components/features/ClientFeedback/ClientFeedback.module.scss
  src/components/features/ClientFeedback/ClientFeedbackContainer.js
  src/components/views/Homepage/Homepage.js
  src/redux/initialState.js
  src/redux/reviewRedux.js
  src/redux/store.js
  src/styles/settings.scss
Labels: conflicts

#30 Wdp200301 34
  public/images/man2.jpg
  public/images/woman.jpg
  src/components/features/ClientFeedback/ClientFeedback.js
  src/components/features/ClientFeedback/ClientFeedback.module.scss
  src/components/views/Homepage/Homepage.js
  src/redux/initialState.js
Labels: conflicts
